version: '3'
services:
  angular.test:
    build:
      context: ./client/.devcontainer
      dockerfile: Dockerfile
    working_dir: /var/www/html/client
    user: node
    command: sh -c "npm install && ng serve --host 0.0.0.0 --public-host 'localhost'"
    expose:
      - '4200'
    volumes:
      - './:/var/www/html'
    networks:
      - marsbots
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./dev-proxy/data/conf.d:/etc/nginx/conf.d
      - ./dev-proxy/data/templates:/etc/nginx/templates
    environment:
      - SERVER_IP=JORDANS-DESKTOP.local
    networks:
      - marsbots
networks:
  marsbots:
